### Get all destinations
GET https://tfhkqqdlphfizlkoxcqo.supabase.co/rest/v1/destinations?select=*
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaGtxcWRscGhmaXpsa294Y3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDY0NjUsImV4cCI6MjA2NDEyMjQ2NX0.iS7tpMwXanVPK5dmwkzYgTyyHbsisHg65bWnijHDwwc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaGtxcWRscGhmaXpsa294Y3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDY0NjUsImV4cCI6MjA2NDEyMjQ2NX0.iS7tpMwXanVPK5dmwkzYgTyyHbsisHg65bWnijHDwwc
Content-Type: application/json

### Test connection with any table
GET https://tfhkqqdlphfizlkoxcqo.supabase.co/rest/v1/destination
apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaGtxcWRscGhmaXpsa294Y3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDY0NjUsImV4cCI6MjA2NDEyMjQ2NX0.iS7tpMwXanVPK5dmwkzYgTyyHbsisHg65bWnijHDwwc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmaGtxcWRscGhmaXpsa294Y3FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDY0NjUsImV4cCI6MjA2NDEyMjQ2NX0.iS7tpMwXanVPK5dmwkzYgTyyHbsisHg65bWnijHDwwc
Content-Type: application/json